lua/git/git.lua
lua/git/ui.lua
tests/unit/git_spec.lua

Changes made in this PR:
- When a diff window is open the cursor position in the current window is mimicked relative to the changes in the diff window
- Refactored some existing functionality
- Added cursorbind to the diff window

Maintain Cursor Position

---

lua/git/init.lua
lua/git/ui.lua

Changes made in this PR:
- Both hunk and diff view sign column text colors can now be customizable

Customizable Colors for texthl for both Hunk and Diff View

---

README.md
lua/vgit/configurer.lua
lua/vgit/defer.lua
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/ui.lua
tests/unit/configurer_spec.lua
tests/unit/init_spec.lua

Changes:
- The user can decide to provide their own configurations
- Added configurer module responsible for dynamically assigning the user configurations accordingly
- Tests
- Updated docs

Configurations

---

README.md
lua/vgit/border.lua
lua/vgit/highlighter.lua
lua/vgit/init.lua
lua/vgit/ui.lua
lua/vgit/view.lua
tests/unit/fs_spec.lua
tests/unit/highlighter_spec.lua

Changes:
- Borders now have titles
- Borders are now implemented
- Native borders are used when title is not present

Border Title

---

README.md
lua/vgit/buffer.lua
lua/vgit/highlighter.lua
lua/vgit/init.lua
tests/unit/init_spec.lua

Changelog:
- Buf Enter and Buf Update is now handled by it's own seperate event
- Rentering buffer no longer will run git computations again

Buffer Optimization

---

lua/vgit/Bstate.lua
lua/vgit/View.lua
lua/vgit/Widget.lua
lua/vgit/buffer.lua
lua/vgit/init.lua
lua/vgit/localization.lua
lua/vgit/ui.lua
tests/unit/Bstate_spec.lua

Changelog:
- Reduced throttle time
- Fixed coroutine scheduling
- Cached filetype for the buffer
- Views now come with a loading and error state
- Widgets also support this feature
- Updated localization

Loading and Error states

---

lua/vgit/init.lua

Changelog:
- Buffer reset originally was done by reseting the current buffer to HEAD, however, it's best if lines at diff base was retrieved and saved instead

Graceful Buffer Reset

---

lua/vgit/init.lua

Changelog:
- Invalid scheduling call prevents loading indicators from being seen

fix sheduling

---

README.md
lua/vgit/fs.lua
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/ui.lua
tests/unit/Bstate_spec.lua

Changelog:
- Hunk signs are now automatically calculated

Hunk Prediction - #35

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
README.md
lua/vgit/View.lua
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/ui.lua
tests/unit/init_spec.lua

Changelog;
- Users can now use the `show_blame` command to see a popup VGit view showing more details about the blame they are on
- Optimized entire application regarding coroutines

Blame Preview + Maintenence

---

lua/vgit/Widget.lua
lua/vgit/ui.lua

Changelog:
- Fix #51
- Added configuration for widgets to have the ability to render a widget as a popup

Widget focus issue without a mouse - #51

---

README.md
lua/vgit/View.lua
lua/vgit/highlighter.lua
lua/vgit/ui.lua

Changelog:
- Implementation for #53

Window Focus Indicator - #53

---

README.md
lua/vgit/highlighter.lua
lua/vgit/init.lua
lua/vgit/ui.lua

Hunk prediction fails when opening and closing buffer multiple times

---

lua/vgit/init.lua
lua/vgit/localization.lua
tests/unit/init_spec.lua

Changelog:
- users can now set their own hunk prediction strategy

Add hunk prediction strategy

---

README.md
lua/vgit/init.lua
lua/vgit/sign.lua
lua/vgit/ui.lua

Changelog:
- Added a bit more abstraction in order to improve feature development in the future

Introduce more abstraction

---

.github/workflows/ci.yml
lua/vgit/View.lua
lua/vgit/Widget.lua
lua/vgit/buffer.lua
lua/vgit/defer.lua
lua/vgit/fs.lua
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/localization.lua
lua/vgit/sign.lua
lua/vgit/ui.lua
lua/vgit/widgets/blame.lua
lua/vgit/widgets/history.lua
lua/vgit/widgets/hunk.lua
lua/vgit/widgets/preview.lua
stylua.toml
tests/unit/Bstate_spec.lua
tests/unit/State_spec.lua
tests/unit/buffer_spec.lua
tests/unit/defer_spec.lua
tests/unit/fs_spec.lua
tests/unit/highlighter_spec.lua
tests/unit/localization_spec.lua
tests/unit/logger_spec.lua

Changelog:
- Added lua code formatter called StyLua

Add lua code formatter

---

README.md
lua/vgit/BlamePopup.lua
lua/vgit/BlamePreviewPopup.lua
lua/vgit/HistoryPopup.lua
lua/vgit/PreviewPopup.lua
lua/vgit/View.lua
lua/vgit/dimensions.lua
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/navigation.lua
lua/vgit/ui.lua

Changelog:
- VGit now supports Blame Previews with the command `:VGit buffer_blame_preview`
- It is similar to the github file blame feature found in the website.

feat #84/#24 - Added Blame Preview

---

lua/vgit/View.lua
lua/vgit/init.lua
lua/vgit/navigation.lua
lua/vgit/ui.lua

Changelog:
- Implemented #95 
- Views now come with some neat animation which can also be configured by the end user

Animated Loading Indicators

---

lua/vgit/View.lua
lua/vgit/popups/DiffPopup.lua

Changelog:
- Made the new diff feature a bit less generic.
- Minor refactoring on View module.

Horizontal diff layout changes

---

lua/vgit/popups/BlamePreviewPopup.lua
lua/vgit/popups/DiffPopup.lua
lua/vgit/popups/HistoryPopup.lua
lua/vgit/popups/PreviewPopup.lua

Changelog:
- Make the layouts fit windows better
- Fix a focus bug

Redesign Layouts

---

lua/vgit/popups/HistoryPopup.lua
lua/vgit/popups/PreviewPopup.lua

Changelog:
- tweaked parameters

minor layout adjustment

---

lua/vgit/init.lua
lua/vgit/previews/HistoryPreview.lua

Changelog:
- removed unwanted coroutine calls

Maintenance Refactor

---

lua/vgit/Popup.lua
lua/vgit/Preview.lua
lua/vgit/builders/TableBuilder.lua
lua/vgit/previews/HistoryPreview.lua
lua/vgit/previews/ProjectDiffPreview.lua
lua/vgit/render_settings.lua
lua/vgit/virtual_text.lua

Changelog:
- Cleaned up Popup class
- Added ability to have popups that are static and is not subject to change
- Static popups no longer flicker if changes are made to the preview
- Added TableBuilder as a part of popup view builders

chore: maintenance refactor

---

README.md
lua/vgit.lua
lua/vgit/Component.lua
lua/vgit/decorators/BorderDecorator.lua
lua/vgit/fs.lua
lua/vgit/layouts/default.lua
lua/vgit/previews/DiffPreview.lua
lua/vgit/previews/HistoryPreview.lua
lua/vgit/previews/ProjectDiffPreview.lua
lua/vgit/themes/monokai.lua
lua/vgit/themes/tokyonight.lua

Changelog:
- Project diff preview now shows icons
- Project diff preview shows highlights

feat: project_diff_preview UI improvements

---

lua/vgit.lua
lua/vgit/Preview.lua
lua/vgit/layouts/default.lua
lua/vgit/navigation.lua
lua/vgit/previews/DiffPreview.lua
lua/vgit/previews/ProjectDiffPreview.lua

Changelog:
- Tweaked navigation slightly

chore: refactor

---

lua/vgit/components/TableComponent.lua
lua/vgit/decorators/AppBarDecorator.lua
lua/vgit/decorators/BorderDecorator.lua
lua/vgit/decorators/VirtualLineNrDecorator.lua
lua/vgit/layouts/default.lua
lua/vgit/previews/HistoryPreview.lua

Changelog:
- Fixed some layout issues
- Made layout more immersive
- Added highlights for hashes in history preview

feat: History preview highlights

---

lua/vgit/cli/Git.lua
lua/vgit/core/Buffer.lua
lua/vgit/core/console.lua
lua/vgit/core/fs.lua
lua/vgit/features/LiveGutter.lua
tests/unit/core/fs_spec.lua

Fix: Issue with submodule

---

lua/vgit/core/Buffer.lua
lua/vgit/features/LiveBlame.lua
lua/vgit/features/LiveGutter.lua

fix: Race condition

---

lua/vgit/features/scenes/HistoryScene.lua
lua/vgit/ui/active_scene.lua

Buffer history not updating on enter

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/Marker.lua
lua/vgit/core/Namespace.lua
lua/vgit/features/BufferHunks.lua
lua/vgit/settings/live_blame.lua

fix: blame line now recognizes years

---

lua/vgit/core/icons.lua
lua/vgit/features/scenes/ProjectDiffScene.lua
lua/vgit/features/scenes/ProjectHunksScene.lua
lua/vgit/ui/components/CodeComponent.lua
lua/vgit/ui/components/PresentationalComponent.lua

fix: icon not found

---

README.md

Just some touch ups to the readme to make it look a bit better.

doc: make it look pretty

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/Command.lua
lua/vgit/Feature.lua
lua/vgit/cli/Git.lua
lua/vgit/core/Job.lua
lua/vgit/core/Namespace.lua
lua/vgit/core/Versioning.lua
lua/vgit/features/AuthorshipCodeLens.lua
lua/vgit/features/BufferHunks.lua
lua/vgit/features/LiveBlame.lua
lua/vgit/features/LiveGutter.lua
lua/vgit/features/ProjectHunksList.lua
lua/vgit/settings/authorship_code_lens.lua
lua/vgit/ui/Scene.lua

Code Lens | Git Authorship

---

README.md
doc/vgit.txt

fix: #216 documentation error

---

lua/vgit/features/buffer/AuthorshipCodeLens.lua

fix: duplicate authorship code lens (#221)

---

lua/vgit.lua
lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/HistoryScreen/init.lua
lua/vgit/features/screens/ProjectCommitsScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/features/screens/ProjectHunksScreen/init.lua
lua/vgit/ui/active_screen.lua

fix: allow hunk_up and hunk_down to directly be used within diffs

---

lua/vgit/features/buffer/AuthorshipCodeLens.lua
lua/vgit/features/buffer/LiveBlame.lua
lua/vgit/features/screens/DiffScreen/Query.lua
lua/vgit/features/screens/GutterBlameScreen/Query.lua
lua/vgit/features/screens/HistoryScreen/Query.lua
lua/vgit/features/screens/ProjectCommitsScreen/Query.lua
lua/vgit/features/screens/ProjectDiffScreen/Query.lua
lua/vgit/git/GitObject.lua

Line blame is now cached for a faster blame retrieval.

chore: live blame optimization

---

README.md
doc/vgit.txt
lua/vgit/core/utils.lua
lua/vgit/features/buffer/Hunks/navigation.lua
lua/vgit/settings/live_gutter.lua

Closes: https://github.com/tanvirtin/vgit.nvim/issues/225

feat: Live Gutter navigation customization

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/features/buffer/Hunks/navigation.lua
lua/vgit/features/screens/ProjectDiffScreen/Mutation.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/settings/project_diff_preview.lua
lua/vgit/ui/active_screen.lua
lua/vgit/ui/components/FoldableListComponent.lua
lua/vgit/ui/views/CodeView.lua
lua/vgit/ui/views/FoldableListView.lua

feat: stage hunks right from project diff preview

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/Command.lua
lua/vgit/core/Buffer.lua
lua/vgit/core/Namespace.lua
lua/vgit/core/utils.lua
lua/vgit/features/screens/DebugScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/Mutation.lua
lua/vgit/features/screens/ProjectHunksScreen/GitFile.lua
lua/vgit/features/screens/ProjectLogsScreen/Query.lua
lua/vgit/features/screens/ProjectLogsScreen/init.lua
lua/vgit/git/GitObject.lua
lua/vgit/git/cli/Git.lua
lua/vgit/settings/hls.lua
lua/vgit/ui/Component.lua
lua/vgit/ui/active_screen.lua
lua/vgit/ui/components/FoldableListComponent.lua
lua/vgit/ui/views/GitLogsView.lua

Closes: #238
- This is not just a screen that shows users logs of their commits in
their current working branch, but it is also interactive.
- Users can <tab> to select the hunks they want to see and send them to
the project_commits_preview
- Users can specify additional flags to this preview window for example:
- :VGit project_logs_preview --author=tanvirtin -n2

Project logs preview

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/features/screens/ProjectDiffScreen/Mutation.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/git/GitObject.lua
lua/vgit/git/cli/Git.lua
lua/vgit/git/cli/models/Patch.lua
lua/vgit/settings/project_diff_preview.lua
lua/vgit/ui/active_screen.lua

feat: unstage hunk in Project Diff Preview

---

lua/vgit.lua
lua/vgit/features/screens/DiffScreen/Mutation.lua
lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/ui/active_screen.lua
lua/vgit/ui/components/CodeComponent.lua

Closes: https://github.com/tanvirtin/vgit.nvim/issues/245

feat: Buffer reset via diff_preview

---

lua/vgit/core/utils.lua
lua/vgit/features/screens/ProjectLogsScreen/init.lua
lua/vgit/ui/views/CodeView.lua
lua/vgit/ui/views/GitLogsView.lua

fix: allow project_logs_preview to open current commit in line if

---

lua/vgit/features/screens/HistoryScreen/init.lua
lua/vgit/ui/views/TableView.lua

Closes: https://github.com/tanvirtin/vgit.nvim/issues/250

feat: connect buffer_history_preview with project_commits_preview

---

Makefile
lua/vgit/core/icons.lua
lua/vgit/features/screens/ProjectCommitsScreen/FSListGenerator.lua
lua/vgit/features/screens/ProjectCommitsScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/features/screens/ProjectHunksScreen/init.lua
lua/vgit/ui/components/FoldableListComponent.lua
lua/vgit/ui/decorations/HeaderTitle.lua
lua/vgit/ui/views/FoldableListView.lua

Closes: https://github.com/tanvirtin/vgit.nvim/issues/252

Project commit tree preview

---

lua/vgit/git/cli/Git.lua
lua/vgit/git/cli/models/Hunk.lua

closes: https://github.com/tanvirtin/vgit.nvim/issues/228

fix: Untracked file hunks have no headers

---

lua/vgit/features/screens/ProjectCommitsScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/settings/hls.lua
lua/vgit/ui/Component.lua
lua/vgit/ui/FSListGenerator.lua
lua/vgit/ui/components/FoldableListComponent.lua
lua/vgit/ui/elements/LineNumberElement.lua
lua/vgit/ui/views/CodeView.lua
lua/vgit/ui/views/FoldableListView.lua

feat: Project diff preview is now a tree

---

lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/ui/ComponentPlot.lua
lua/vgit/ui/components/FooterComponent.lua
lua/vgit/ui/views/FooterView.lua

Effected views:
- diff_staged_preview
- buffer_diff_staged_preview
- project_diff_preview

feat: keymap help footer

---

lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/settings/hls.lua
lua/vgit/ui/components/AppBarComponent.lua
lua/vgit/ui/views/AppBarView.lua
lua/vgit/ui/views/CodeView.lua

Footer is now app bar placed on top of a view.

fix: footer overlap

---

lua/vgit/core/highlight.lua

fix(#287) issue with colorscheme switching event handler

---

lua/vgit/features/screens/ProjectCommitsScreen/Store.lua
lua/vgit/features/screens/ProjectCommitsScreen/init.lua

Users are now able to open a file from project_commits_preview when they press enter on either the list or the diff preview.

feat(project_commits_preview): add support for opening files

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/Command.lua
lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/ProjectCommitScreen/Mutation.lua
lua/vgit/features/screens/ProjectCommitScreen/Store.lua
lua/vgit/features/screens/ProjectCommitScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/git/cli/Git.lua
lua/vgit/settings/project_commit_preview.lua
lua/vgit/settings/project_diff_preview.lua
lua/vgit/ui/Component.lua
lua/vgit/ui/screen_manager.lua
lua/vgit/ui/views/SimpleView.lua

feat(project_commit_preview): add ability to commit changes

---

lua/vgit/core/Buffer.lua
lua/vgit/core/Namespace.lua
lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/ui/Component.lua
lua/vgit/ui/views/AppBarView.lua

- This improves help bar highlights of project_diff_preview and buffer_diff_preview.

feat: added lua pattern highlight

---

lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/HistoryScreen/init.lua
lua/vgit/features/screens/ProjectCommitScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua

- Added row layout mechanism to buffer_history_preview to dynamically calculate row positionining
- Added additional highlighting for project_commit_preview, project_diff_preview and buffer_diff_preview

style: fix misc issues

---

lua/vgit/features/screens/ProjectDiffScreen/Store.lua

- Allow changes with conflicts to show up in project_diff_preview

feat(project_diff_preview): show merge changes

---

lua/vgit/core/ReadStream.lua

Fix https://github.com/tanvirtin/vgit.nvim/issues/348

Optimize std out parsing

---

lua/vgit/features/screens/ProjectLogsScreen/init.lua

fix(#343): fix project_logs_preview

---

lua/vgit/features/screens/HistoryScreen/init.lua
lua/vgit/features/screens/ProjectCommitsScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/features/screens/ProjectHunksScreen/init.lua

closes https://github.com/tanvirtin/vgit.nvim/issues/344

screens | replace j, k with event CursorMoved

---

doc/vgit.txt

#343 | fix vimdoc

---

lua/vgit/git/cli/Git.lua

fix(#361): fix diff functionality not working when cwd does not match .git folder

---

lua/vgit/features/buffer/LiveGutter.lua

fix(#366): live gutter will no longer fetch data if it is disabled

---

README.md
doc/vgit.txt
lua/vgit/core/Buffer.lua
lua/vgit/core/keymap.lua
lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/LineBlameScreen/init.lua
lua/vgit/features/screens/ProjectCommitScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/features/screens/ProjectLogsScreen/init.lua
lua/vgit/features/screens/ProjectStashScreen/init.lua
lua/vgit/settings/diff_preview.lua
lua/vgit/settings/project_commit_preview.lua
lua/vgit/settings/project_diff_preview.lua
lua/vgit/settings/project_logs_preview.lua
lua/vgit/settings/project_stash_preview.lua
lua/vgit/ui/Component.lua
lua/vgit/ui/screen_manager.lua
lua/vgit/ui/views/BlameListView.lua
lua/vgit/ui/views/DiffView.lua
lua/vgit/ui/views/KeyHelpBarView.lua
lua/vgit/ui/views/LineBlameView.lua
lua/vgit/ui/views/PaginationView.lua
lua/vgit/ui/views/SimpleView.lua
lua/vgit/ui/views/StatusListView/init.lua
lua/vgit/ui/views/TableView.lua

feat(#377): add keymap descriptions

---

lua/vgit/ui/views/DiffView.lua

fix(#384): fix word diff no longer rendering

---

README.md
lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/features/screens/ProjectCommitScreen/init.lua
lua/vgit/features/screens/ProjectDiffScreen/init.lua
lua/vgit/features/screens/ProjectStashScreen/init.lua
lua/vgit/ui/views/KeyHelpBarView.lua

fix(#388): fix incompatibility with old setups

---

lua/vgit/controller.lua
lua/vgit/ui/Scene.lua
lua/vgit/ui/screen_manager.lua

fix(#397): fix issue where scene quit keys would be binded globally

---

lua/vgit/git/GitBuffer.lua
lua/vgit/git/git_buffer_store.lua
lua/vgit/git/git_hunks.lua

fix(#395): fix race condition around buffer attachment

---

lua/vgit/core/Buffer.lua
lua/vgit/git/GitBuffer.lua
lua/vgit/ui/Extmark.lua

fix(#413): ensure ns_id for each extmark category type is unique
