tanvirtin/vgit.nvim

README.md
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/ui.lua
tests/unit/git_spec.lua
tests/unit/init_spec.lua

Changes:
- All project hunks can now be navigatable via a new command called hunks_quickfix
- The user can then use all quickfix commands to navigate between all the hunks in the project
- Previously origin buffer was not focusable, this is no longer the case
- ESC now also closes the diff window

Quickfix Hunks

---

README.md
lua/vgit/Bstate.lua
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/localization.lua
tests/unit/Bstate_spec.lua
tests/unit/git_spec.lua
tests/unit/init_spec.lua

Changelog:
- Added `get_diff_base` and `set_diff_base` which can be used to retrieve and set the current diff base on the fly
- Invalid diff base commit hash will result in a error warning and diff wont be set
- Update documentation

Ability to change diff base on the fly

---

lua/vgit/View.lua
lua/vgit/ui.lua

Changelog:
- Views are now focusable with a new method called `focus`
- Buffer history view now has the logs focused by default
- Buffer Preview view now has current window focused by default

Views are focusable

---

lua/vgit/ui.lua

Changelog:
- All previews don't use the same namespace for signs as the parent buffer
- This allows to wipe out any signs that we don't need

Fix signs being shown despite an error occuring

---

README.md
lua/vgit/fs.lua
lua/vgit/git.lua
lua/vgit/init.lua
lua/vgit/localization.lua
tests/unit/git_spec.lua
tests/unit/init_spec.lua

Changelog:
- Added Diff Strategy feature.
- Now users can choose how to calculate the diff across their entire project.
- All diff in the repository can now be directly compared to the index of the repository rather than the actual HEAD.
- The user gets two options 'remote' and 'index', by default it's remote. When the user sets it to index all hunks, and buffer preview will now be relative to the repository and the staging that the user does.
- Fixed an issue where timeout error was shown when retrieving logs for extremely large repositories.
- Fixed an error with blame toggle.

Diff Strategy

---

lua/vgit/core/Buffer.lua
lua/vgit/core/GitObject.lua
lua/vgit/core/Versioning.lua
lua/vgit/core/fs.lua
lua/vgit/features/LiveGutter.lua
lua/vgit/ui/Component.lua
lua/vgit/ui/abstract_scenes/CodeDataScene.lua
lua/vgit/ui/abstract_scenes/CodeScene.lua
lua/vgit/ui/components/CodeComponent.lua
lua/vgit/ui/components/PopupComponent.lua
lua/vgit/ui/components/PresentationalComponent.lua
lua/vgit/ui/elements/LineNumberElement.lua
tests/unit/cli/Git_spec.lua
tests/unit/core/GitObject_spec.lua

- blame line realizes years
- vim.diff is used on specific versions
- plugin no longer manages treesitter logic, simply delegates the work to neovim who should be intelligent enough to set everything up

chore: refactor

---

README.md
lua/vgit/Diff.lua
lua/vgit/features/scenes/DiffScene.lua
lua/vgit/features/scenes/GutterBlameScene.lua
lua/vgit/features/scenes/HistoryScene.lua
lua/vgit/features/scenes/ProjectDiffScene.lua
lua/vgit/features/scenes/ProjectHunksScene.lua
lua/vgit/ui/abstract_scenes/CodeDataScene.lua
lua/vgit/ui/abstract_scenes/CodeScene.lua
lua/vgit/ui/components/TableComponent.lua

Closes #171
You can navigate hunks using "hunk_up" and "hunk_down" either you are focused on the table or the code view. 
I suggest binding these navigation command to a useful keymapping.
Pressing `<CR>` either on table or code view will take you directly to the hunk you were navigating when you open the buffer.
Additionally, just being on any hunk and pressing enter should take you to the hunk you are on when you are focused on the code view.

feat: Project Diff Preview | Goto hunks

---

lua/vgit/settings/symbols.lua
lua/vgit/ui/screens/CodeScreen.lua

default `vgit.settings.symbols` config should not have a `"symbols"` key.
With the symbols key, after user-defined configuration is incorrectly applied 
The `Object:data` table goes from:
```
data = {
symbols = {
void = '⣿'
}
}
```
to 
```
data = {
symbols = {
void = '⣿'
},
void = '^' -- whatever char the user defined
}
```

fix: symbols default config should not have symbols key

---

lua/vgit/core/Buffer.lua
lua/vgit/features/buffer/LiveGutter.lua
lua/vgit/git/GitObject.lua

As requested in #218, separate PR to fix #157, #212 rebased for the latest changes.
I did note a bug that didn't exist before https://github.com/tanvirtin/vgit.nvim/commit/e5ba3240258a5097eb149369136e2663dd3d5e71, when opening a non-tracked file `hunk.stat` shows all lines of the current buffer as `added`, this happens on files even outside of the current repo path.

feat: added buffer var with current diff stats (#157, #212)

---

lua/vgit.lua
lua/vgit/core/fs.lua
lua/vgit/core/utils.lua
lua/vgit/git/cli/Git.lua
lua/vgit/settings/git.lua

Title: should solve #149.
First, ty for this wonderful plugin, love the meticiousness of your code :-)
That said, before I continue further with this PR (doc, testing, etc) I want to make sure this is how you'd approach it (settings inside `cli/Git.lua` and my `fallback_args` approach).
This PR adds a test for each new `GitObject` coming from a buffer (i.e. has `GitObject`) if the current file is inside a git a dir, if not it will use a new `cwd` as well as supply `--git-dir` and `--work-tree` to the git command so that `vgit` can find the hunks, etc, basically replacing the `git` command with `git --git-dir <path> --work-tree <path>`.
In order to use the new setting you need to add the below to your setup:
```lua
require("vgit").setup {
settings = {
git = {
cmd = 'git', -- optional …
```

feat: add fallback bare repo (yadm support)

---

lua/vgit/core/Buffer.lua
lua/vgit/features/buffer/LiveGutter.lua

- Fixed a typo where `local live_signs = buffer:clear_cached_live_signs()` was being called over `local live_signs = buffer:get_cached_live_signs()`.
- `LiveGutter:sync` ensures that the buffer for which signs are shown is valid.

fix: check if buffer is valid before syncing live gutter

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/core/loop.lua
lua/vgit/features/screens/DiffScreen/Mutation.lua
lua/vgit/features/screens/DiffScreen/Query.lua
lua/vgit/features/screens/DiffScreen/init.lua
lua/vgit/git/cli/models/Patch.lua
lua/vgit/settings/diff_preview.lua
lua/vgit/ui/active_screen.lua
lua/vgit/ui/views/CodeView.lua

Closes: https://github.com/tanvirtin/vgit.nvim/issues/114
Users are given the ability to do the following:
- Stage all hunks in "diff_preview" and "hunk_preview" pressing "S"
- Unstage all hunks in "diff_preview" and "hunk_preview" pressing "U"
- Stage a hunk in "diff_preview" and "hunk_preview" pressing "s" on a hunk
- Unstage a hunk in "staged_diff_preview" and "hunk_staged_preview" pressing "u" on a hunk
- Switch between unstage and staged version of the view by pressing "t"

DiffScreen enhancements

---

README.md
doc/vgit.txt
lua/vgit.lua
lua/vgit/Command.lua
lua/vgit/features/screens/ProjectCommitsScreen/FSListGenerator.lua
lua/vgit/features/screens/ProjectCommitsScreen/Query.lua
lua/vgit/features/screens/ProjectStashScreen/Query.lua
lua/vgit/features/screens/ProjectStashScreen/init.lua
lua/vgit/git/cli/Git.lua
lua/vgit/ui/active_screen.lua

Closes: https://github.com/tanvirtin/vgit.nvim/issues/248
- Executing the command `:VGit project_stash_preview` will open a VGit
preview of all stashed entries in your project.
- Users can press <tab> to select the stashes
- Pressing enter will show all changes associated with the selected
stashes in `project_commits_preview`.
- If nothing is selected, then the entry on the current line will be
sent to `project_commits_preview`

feat: project_stash_preview

---

lua/vgit/ui/screen_manager.lua

Fixes #297 `<C-c>` mapping is not necessary as  users can define their own mapping to quit screens.

fix(keymapping): revert <C-c> mapping to close screen previews

---

lua/vgit/git/cli/Git.lua

Hi tanvirtin,
When cwd is outside of the root git directory, calls to git show fail due to the `./` prefix added to the filename. I believe this is not required, since we should be using a relative filename from the project git root dir and/or setting `-C` to self.cwd.
To replicate, open any file in a root git directory, `:cd` to some other dir and `:VGit buffer_blame_preview`
```Error executing luv callback:                                                                                                                                                                                                                                  
...ocal/share/nvim/plugged/vgit.nvim/lua/vgit/core/loop.lua:43: coroutine failed :: function: 0x7f583cfe90f8 …
```

fix(git show): allow cwd outside root git dir

---

lua/vgit/git/cli/Git.lua

Hi tanvirtin,
Apologies, noticed today last commit breaks a few things. This is what we wanted.
Commit e0fe17114 ("fix(git show): allow cwd outside root git dir") removed the "./" prefix before the filename when cwd did not equal the root git dir.
Some aspects of VGit like live gutter and hunk preview rely on this, so replace with self.cwd instead.
Thanks

fix(git show): cwd is sometimes required

---

lua/vgit/controller.lua
lua/vgit/features/buffer/Hunks.lua
lua/vgit/features/buffer/LiveGutter.lua
lua/vgit/git/GitBuffer.lua

fix(#378): fix runtime error on execution

---

lua/vgit/git/git_repo.lua

I have an issue that is hard to reproduce in astronvim+lazygit.nvim, so I have just debugged it and found the source issue.
There is no handling in the case that for some reason, the git command line returned an empty "stderr"(really, don't know why, maybe command line failures of NVIM for some moments), but the command has exited with a non-zero code. We shall check the return code anyway, however I give here an alternative solution.
Here is a patch that checks that for the directory queries if the result stdout is empty, and if so, it returns a non-nil error `{}`.
If you have a better solution, go ahead. Sorry for not including reproduction, but this suggestion makes the code safer anyway.
Thanks for this great project BTW!
Fixes #403

Safer handling of the git command results

---

lua/vgit/ui/Extmark.lua

This way, the extmarks can be filtered for the purposes of plugins like statuscol.nvim.

feat: create extmarks in a named namespace

---

lua/vgit/core/assertion.lua
lua/vgit/core/console.lua

fix(#412): remove deprecated method usage -- vim.tbl_islist
